app/Main.hs
smash.cabal
src/Cardano/Db/Query.hs
src/Cardano/Db/Schema.hs
src/Cardano/SmashDbSync.hs
src/DB.hs
src/DbSyncPlugin.hs

https://jira.iohk.io/browse/CAD-1330

[CAD-1330] Add http client for fetching JSON metadata.

---

src/DbSyncPlugin.hs

https://jira.iohk.io/browse/CAD-1353

[CAD-1353] Add JSON size check for offline metadata.

---

app/Main.hs
cabal.project
config/mainnet-config.yaml
src/Cardano/Db/Database.hs
src/Cardano/Db/Schema.hs
src/Cardano/SmashDbSync.hs
src/DbSyncPlugin.hs
src/Lib.hs
stack.yaml
stack.yaml.lock
test/SmashSpecSM.hs

https://jira.iohk.io/browse/CAD-1371
Currently working with MC4, ignoring Byron blocks. Run with:
```
nix-build -A scripts.mainnet_candidate_4.node -o mc4-node
./mc4-node
```
The SMASH server can be run using:
```
SMASHPGPASSFILE=config/pgpass ./scripts/postgresql-setup.sh --recreatedb
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-migrations --mdir ./schema
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- create-migration --mdir ./schema
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-migrations --mdir ./schema
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-app-with-db-sync --config config/mainnet-config.yaml --socket-path ../cardano-node/state-node-mainnet_candidate_4/node.socket --schema-dir schema/
```
Synced up to the tip, blacklisting working.

[CAD-1371] Integrate SMASH against HFC.

---

schema/migration-2-0002-20200805.sql
schema/migration-2-0002-20200806.sql
smash.cabal
src/Cardano/Db/Schema.hs
src/Cardano/SmashDbSync.hs
src/DB.hs
src/DbSyncPlugin.hs
src/FetchQueue.hs
src/FetchQueue/Retry.hs
src/Lib.hs
src/Offline.hs
test/SmashSpecSM.hs

I would prefer not to merge this before QA has looked at it.

Add asynchronous updating of offline metadata

---

README.md
app/Main.hs
src/Cardano/Db/Error.hs
src/Cardano/Db/Insert.hs
src/DB.hs

https://jira.iohk.io/browse/CAD-1462
Based on https://github.com/input-output-hk/smash/pull/45
Improvement reported by @dorin100 
Example:
```
$> SMASHPGPASSFILE=config/pgpass stack run smash-exe -- reserve-ticker-name --tickerName "EARTH" --poolhash "0bbae0287d0ee96cc63b07cc18d25483d9010282ac726c35f450ea8622036e87"
Reserving ticker name!
Adding reserved ticker 'EARTH' with hash: PoolMetadataHash {getPoolMetadataHash = "0bbae0287d0ee96cc63b07cc18d25483d9010282ac726c35f450ea8622036e87"}
Ticker name inserted into the database reserved!
$> SMASHPGPASSFILE=config/pgpass stack run smash-exe -- reserve-ticker-name --tickerName "EARTH" --poolhash "0bbae0287d0ee96cc63b07cc18d25483d9010282ac726c35f450ea8622036e87"
Reserving ticker name!
Adding reserved ticker 'EARTH' with hash: PoolMetadataHash …
```

[CAD-1462] Clarify insert ticker command name and report error if ticker already exists

---

doc/getting-started/how-to-install-smash.md
schema/migration-2-0002-20200904.sql
smash.cabal
src/Cardano/Db/Insert.hs
src/Cardano/Db/Query.hs
src/Cardano/Db/Schema.hs
src/Cardano/Db/Types.hs
src/Cardano/SmashDbSync.hs
src/DB.hs
src/DbSyncPlugin.hs
src/FetchQueue.hs
src/Lib.hs
src/Offline.hs
src/Types.hs
test/SmashSpecSM.hs

https://jira.iohk.io/browse/CAD-1744
There are two ways to query errors:
```
http://localhost:3100/api/v1/errors
```
And if you have the pool id:
```
http://localhost:3100/api/v1/errors?poolId=c0b0e43213a8c898e373928fbfc3df81ee77c0df7dadc3ad6e5bae17
```
Also changed the default flag to enable Basic Auth so people don't forget about that.
Also changed the types to `Text` so we can nicely see them in the DB.

[CAD-1744] Easily query reason for pool metadata lookup failure.

---

src/Cardano/Db/Query.hs
src/DB.hs
src/Lib.hs

https://jira.iohk.io/browse/CAD-1824
Testing can be done like this.
If there are no delisted pools, the returning list should be empty:
```
curl --verbose --header "Content-Type: application/json" localhost:3100/api/v1/delisted
```
```
[]
```
You need to delist the existing `poolId` (or several if you want to see several):
```
curl --user ksaric:cirask --verbose --header "Content-Type: application/json" --request PATCH --data '{"poolId":"fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38"}' http://localhost:3100/api/v1/delist
curl --user ksaric:cirask --verbose --header "Content-Type: application/json" --request PATCH --data '{"poolId":"cbf68681bbd1758480391706a9717fad6cecd668d3903552364a5d9f"}' http://localhost:3100/api/v1/delist
curl --user ksaric:cirask --verbose --header …
```

[CAD-1824] List of delisted Stake pools.

---

doc/getting-started/how-to-install-smash.md
schema/migration-2-0004-20201006.sql
smash.cabal
src/Cardano/Db/Insert.hs
src/Cardano/Db/Query.hs
src/Cardano/Db/Schema.hs
src/DB.hs
src/DbSyncPlugin.hs
src/Lib.hs

https://jira.iohk.io/browse/CAD-1926
Tested on `qa-shelley`.
Testing instructions. You first need to enable `TESTING_MODE`. When you do that you can check the existing metadata:
```
curl --verbose --header "Content-Type: application/json" http://localhost:3100/api/v1/metadata/fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38/93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97
```
Check the retired pools:
```
curl --verbose --header "Content-Type: application/json" http://localhost:3100/api/v1/retired
```
Then add a retired pool (simulate what the chain will do, this is why we need `TESTING_MODE`):
```
curl --verbose --header "Content-Type: application/json" --request PATCH --data '{"poolId":"fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38"}' …
```

[CAD-1926] Retired pools should be ignored.

---

doc/getting-started/how-to-install-smash.md
src/Cardano/Db/Query.hs
src/DB.hs
src/Lib.hs
src/Types.hs

https://jira.iohk.io/browse/CAD-1823
Tested on `mainnet`.
You can find a poolId which contains the errors, like `6b6164af70861c5537cc9c8e50fdae35139ca2c8c6fbb42e8b7e6bfb`.
From there you can see all the errors **from a day ago**:
```
http://localhost:3100/api/v1/errors/6b6164af70861c5537cc9c8e50fdae35139ca2c8c6fbb42e8b7e6bfb
```
Or you can filter from a date:
```
http://localhost:3100/api/v1/errors/6b6164af70861c5537cc9c8e50fdae35139ca2c8c6fbb42e8b7e6bfb?fromDate=15.10.2020
```

[CAD-1823] Stake pools with issues list.

---

src/Offline.hs
src/Types.hs

https://jira.iohk.io/browse/CAD-2061
The example of the new errors can be seen in the logs and in the database:
```
[smash-node.fetch:Warning:49] [2020-10-16 10:49:04.24 UTC] Hash mismatch from poolId '351d8435256ab7f560255342dd464f7becf8e3bc4f976e0d80a90ef9' when fetching metadata from 'http://adajapan.com/poolMetadata.json'. Expected 0aaea3edecb189fc0b033eec805aff362764e3273997a67ef089f3800bcd9af7 but got 407248607ad13e678b3f7f41509c38d9877287dc0a6f4b4a4127d5d443aae37d.
```
```
[smash-node.fetch:Warning:49] [2020-10-16 10:54:43.50 UTC] Offline pool data from poolId '48cdc5d38323c6ac7d0160dedcbbf0661518a57e4699e618fb86424a' when fetching metadata from 'http://poolpros.tech/poolpros.json' exceeded 512 bytes.
```

[CAD-2061] Logs improvement, add information to why an error occured.

---

app/Main.hs
doc/getting-started/how-to-run-smash.md
smash.cabal
src/Cardano/SMASH/API.hs
src/Cardano/SMASH/DB.hs
src/Cardano/SMASH/Lib.hs
src/Cardano/SMASH/Types.hs

1. expose a cli option to start the stub server in test-mode
2. add an endpoint to insert pool metadata manually in test-mode
Related: #97

Improve stub server

---

ChangeLog.md
smash.cabal

The PRs that include clear testing information:
- https://github.com/input-output-hk/smash/pull/90
- https://github.com/input-output-hk/smash/pull/83
- https://github.com/input-output-hk/smash/pull/87
- https://github.com/input-output-hk/smash/pull/89
- https://github.com/input-output-hk/smash/pull/94
- https://github.com/input-output-hk/smash/pull/101
The PRs that are somewhat more complicated to explain how to test:
- https://github.com/input-output-hk/smash/pull/100 - this PR simply changes the genesis files location to be relative to the configuration file
- https://github.com/input-output-hk/smash/pull/80 - this should return the caching header "Cache: Always" when fetching the metadata endpoint

Release 1.2.0.

---

.gitignore
default.nix
nix/nixos/default.nix
nix/nixos/module-list.nix
nix/nixos/smash-service.nix
nix/pkgs.nix
nix/scripts.nix
nix/sources.json

* adds `scripts.<env>.smash` for local testing
* fixes smash config file to have the legacy db-sync config params pulled from nodeConfig
* Defaults RUNTIME_DIRECTORY to $(pwd)
Tested local script as well as deployment on testnet.

nix: add scripts and fix config file

---

smash-servant-types/src/Cardano/SMASH/DBSync/Db/Error.hs
smash/smash.cabal
smash/src/Cardano/SMASH/DB.hs
smash/src/Cardano/SMASH/DBSync/Db/Insert.hs
smash/src/Cardano/SMASH/DBSyncPlugin.hs
smash/test/MigrationSpec.hs

https://jira.iohk.io/browse/CAD-736
Also fixed the failing tests.

[CAD-2181] All queries that don't return anything should return 404

---

smash-servant-types/smash-servant-types.cabal
smash-servant-types/src/Cardano/SMASH/Types.hs

https://jira.iohk.io/browse/CAD-2176
When we submit an ill-formatted pool id we will get 400 Bad Request since the URL doesn't match.
Example:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38 | jq .
Note: Unnecessary use of -X or --request, GET is already inferred.
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:3100...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3100 (#0)
> GET /api/v1/errors/fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38 HTTP/1.1
> Host: localhost:3100
> …
```

[CAD-2176] errors endpoint doesn't validate poolId properly.

---

smash-servant-types/smash-servant-types.cabal
smash-servant-types/src/Cardano/SMASH/API.hs
smash-servant-types/src/Cardano/SMASH/DBSync/Db/Types.hs
smash-servant-types/src/Cardano/SMASH/Types.hs
smash/src/Cardano/SMASH/DBSync/Db/Insert.hs
smash/src/Cardano/SMASH/Lib.hs
stack.yaml

https://jira.iohk.io/browse/CAD-2179
Also added validation to the `TickerName`.
Example of how to test.
Let's see what is delisted:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/delisted
[]
```
And let's delist a couple of them now:
```
$> curl --verbose --user ksaric:cirask --header "Content-Type: application/json" --request PATCH --data '{"poolId":"e5cb8a89cabad2cb22ea85423bcbbe270f292be3dbe838948456d3ae"}' http://localhost:3100/api/v1/delist
{"poolId":"e5cb8a89cabad2cb22ea85423bcbbe270f292be3dbe838948456d3ae"}
```
But what happens if I try to do that with a wrong format (added `e` at the end):
```
$> curl --verbose --user ksaric:cirask --header "Content-Type: application/json" --request PATCH --data …
```

[CAD-2179] pool_id delist endpoint is returning 200 for any string (not only for valid pool_ids).

---

default.nix
nix/nixos/tests/smash-test.nix
nix/pkgs.nix
release.nix

since it is the revision used for prod deployment.

Use own cardano-node revision for integration test

---

ChangeLog.md
doc/getting-started/how-to-install-smash.md
doc/getting-started/how-to-run-smash.md
nix/nixos/smash-service.nix
smash-servant-types/smash-servant-types.cabal
smash/smash.cabal
stack.yaml

Directly depends on https://github.com/input-output-hk/smash/pull/127, the PRs from the changelog contain the info about how to test them.
Also important to note that it depends on `cardano-db-sync` 7.1.
PRs:
- https://github.com/input-output-hk/smash/pull/112
- https://github.com/input-output-hk/smash/pull/122
- https://github.com/input-output-hk/smash/pull/123
- https://github.com/input-output-hk/smash/pull/125
- https://github.com/input-output-hk/smash/pull/124
- https://github.com/input-output-hk/smash/pull/117
- https://github.com/input-output-hk/smash/pull/119
- https://github.com/input-output-hk/smash/pull/121

Release 1.3.0.

---

nix/nixos/smash-service.nix
smash-servant-types/src/Cardano/SMASH/DBSync/Db/Types.hs
smash-servant-types/src/Cardano/SMASH/Types.hs
smash/src/Cardano/SMASH/Lib.hs

https://jira.iohk.io/browse/CAD-2184
This requires migration to OpenAPI and it's quite rigid (but that isn't really stable right now), ideally, it should be done from scratch.

[CAD-2184] Fix Swagger documentation to be consistent, add more info.

---

schema/force-resync.sql
schema/migration-2-0006-20210108.sql
smash-servant-types/src/Cardano/SMASH/API.hs
smash/app/Main.hs
smash/smash.cabal
smash/src/Cardano/SMASH/DB.hs
smash/src/Cardano/SMASH/DBSync/Db/Insert.hs
smash/src/Cardano/SMASH/DBSync/Db/Migration.hs
smash/src/Cardano/SMASH/DBSync/Db/Query.hs
smash/src/Cardano/SMASH/DBSync/Db/Schema.hs
smash/src/Cardano/SMASH/DBSyncPlugin.hs
smash/src/Cardano/SMASH/Lib.hs
smash/src/Cardano/SMASH/Offline.hs
smash/test/MigrationSpec.hs

https://jira.iohk.io/browse/CAD-2449
This works correctly but **requires the full resync from the blockchain** since we need to add pool ids from the beginning of the blockchain.
This can be achieved using the added command which removes all blockchain-related state and forces a resync:
```
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- force-resync --mdir ./schema --config config/shelley-qa-config.yaml
```
Example of how it works.
The existing pool id:
```
curl -X GET http://localhost:3100/api/v1/exists/8517fa7042cb9494818861c53c87780b4975c0bd402e3ed85168aa66 
{"poolId":"8517fa7042cb9494818861c53c87780b4975c0bd402e3ed85168aa66"}
```
Non-existing pool id:
```
curl -X GET http://localhost:3100/api/v1/exists/8517fa7042cb9494818861c53c87780b4975c0bd402e3ed85168aa65 …
```

[CAD-2449] Add API endpoint for checking valid pool id.

---

schema/migration-2-0007-20210114.sql
smash-servant-types/src/Cardano/SMASH/API.hs
smash-servant-types/src/Cardano/SMASH/Types.hs
smash/src/Cardano/SMASH/DB.hs
smash/src/Cardano/SMASH/DBSync/Db/Delete.hs
smash/src/Cardano/SMASH/DBSync/Db/Query.hs
smash/src/Cardano/SMASH/DBSync/Db/Schema.hs
smash/src/Cardano/SMASH/DBSyncPlugin.hs
smash/src/Cardano/SMASH/Lib.hs
smash/test/MigrationSpec.hs
smash/test/SmashSpec.hs

https://jira.iohk.io/browse/CAD-2476
Testing this could be done by manually inserting the pool id into the retired pools and before the pool id is picked up from the blockchain (which results in a revive) and after (which results in pool id not existing anymore):
```
SMASHPGPASSFILE=config/pgpass ./scripts/postgresql-setup.sh --recreatedb
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-migrations --mdir ./schema --config config/shelley-qa-config.yaml
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-app --config config/shelley-qa-config.yaml
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- run-app-with-db-sync --config config/shelley-qa-config.yaml --socket-path ../cardano-node/state-node-shelley_qa/node.socket --state-dir ledger-state/shelley-qa --schema-dir schema/ …
```

[CAD-2476] SMASH not returning active pools that were previously retired

---

smash-servant-types/smash-servant-types.cabal
smash-servant-types/src/Cardano/SMASH/API.hs
smash-servant-types/src/Cardano/SMASH/Types.hs
smash/smash.cabal
smash/src/Cardano/SMASH/DB.hs
smash/src/Cardano/SMASH/HttpClient.hs
smash/src/Cardano/SMASH/Lib.hs

https://jira.iohk.io/browse/CAD-2724

[CAD-2724] CLI option to switch to existing SMASH server filtering.

---

cabal.project
nix/sources.json
smash-servant-types/src/Cardano/SMASH/DBSync/Db/Types.hs
smash/app/Main.hs
smash/smash.cabal
smash/src/Cardano/SMASH/DB.hs
smash/src/Cardano/SMASH/DBSync/Db/Delete.hs
smash/src/Cardano/SMASH/DBSync/Db/Insert.hs
smash/src/Cardano/SMASH/DBSync/Db/Migration.hs
smash/src/Cardano/SMASH/DBSync/Db/Migration/Haskell.hs
smash/src/Cardano/SMASH/DBSync/Db/PGConfig.hs
smash/src/Cardano/SMASH/DBSync/Db/Query.hs
smash/src/Cardano/SMASH/DBSync/Db/Run.hs
smash/src/Cardano/SMASH/DBSync/Db/Schema.hs
smash/src/Cardano/SMASH/DBSync/Metrics.hs
smash/src/Cardano/SMASH/DBSyncPlugin.hs
smash/src/Cardano/SMASH/Offline.hs
smash/test/MigrationSpec.hs
stack.yaml

https://jira.iohk.io/browse/CAD-2060
Updating dependencies for `smash` to match the new `db-sync` version so we can add a plugin to the newest version of `db-sync`.
Tested syncing on `mainnet` - `Insert 'Shelley' block pool info: epoch 229, slot 186000, block BlockNo 4947749, global slot 99114000 `

[CAD-2060] SMASH cache, update SMASH with new db-sync version deps.

---

cabal.project
stack.yaml

https://jira.iohk.io/browse/CAD-2060
Using latest commit hash, having issues with building `db-sync` when referencing `smash` repo.

[CAD-2060] Bumping dependencies for new db-sync.
