input-output-hk/smash

.buildkite/pipeline.yml, .gitignore, scripts/buildkite/default.nix, scripts/buildkite/rebuild.hs, scripts/buildkite/stack-cabal-sync.sh, scripts/nix/stack-shell.nix
https://jira.iohk.io/browse/CAD-751
=> [CAD-751] Add CI to the stake pool metadata aggregation server.

README.md, app/Main.hs, cabal.project, default.nix, nix/haskell.nix, nix/pkgs.nix, nix/stack-shell.nix, shell.nix, smash.cabal, src/Lib.hs, stack.yaml, stack.yaml.lock
https://jira.iohk.io/browse/CAD-760
=> [CAD-760] Add cardano-prelude.

README.md, app/Main.hs, smash.cabal, src/Lib.hs
https://jira.iohk.io/browse/CAD-762
=> [CAD-762] Initial API design

smash.cabal, src/DB.hs, src/Lib.hs, src/Types.hs
https://jira.iohk.io/browse/CAD-770
=> [CAD-770] Add a simple in-memory database.

.gitignore, app/Main.hs, smash.cabal, src/DB.hs, src/Lib.hs, src/Types.hs, stack.yaml, test/SmashSpec.hs, test/Spec.hs
https://jira.iohk.io/browse/CAD-777
=> [CAD-777] Add simple tests.

README.md, smash.cabal, src/DB.hs, src/Lib.hs, src/Types.hs, stack.yaml, stack.yaml.lock, test/SmashSpec.hs, test/SmashSpecSM.hs, test/Spec.hs
https://jira.iohk.io/browse/CAD-736
Adding validation for the JSON object.
=> [CAD-1249] Simple state machine tests.

app/Main.hs, schema/migration-2-0002-20200626.sql, schema/migration-2-0003-20200630.sql, smash.cabal, src/Cardano/Db/Database.hs, src/Cardano/Db/Insert.hs, src/Cardano/Db/Migration.hs, src/Cardano/Db/PGConfig.hs, src/Cardano/Db/Query.hs, src/Cardano/Db/Schema.hs, src/Cardano/SmashDbSync.hs, src/DB.hs, src/DbSyncPlugin.hs, stack.yaml, stack.yaml.lock
https://jira.iohk.io/browse/CAD-1266
=> [CAD-1266] Adapt cardano-db-sync for SMASH.

config/mainnet-config.yaml, config/testnet-config.yaml, schema/migration-2-0004-20200710.sql, src/Cardano/Db/Database.hs, src/Cardano/Db/Error.hs, src/Cardano/Db/Insert.hs, src/Cardano/Db/Query.hs, src/Cardano/Db/Schema.hs, src/Cardano/SmashDbSync.hs, src/DbSyncPlugin.hs, src/Lib.hs
https://jira.iohk.io/browse/CAD-1348
Also fixed https://github.com/input-output-hk/smash/issues/16
=> [CAD-1348] Add block insertion so we don't sync from scratch.

README.md, schema/migration-2-0005-20200722.sql, smash.cabal, src/Cardano/Db/Error.hs, src/Cardano/Db/Insert.hs, src/Cardano/Db/Query.hs, src/Cardano/Db/Schema.hs, src/DB.hs, src/Lib.hs, src/Types.hs, test/SmashSpec.hs
https://jira.iohk.io/browse/CAD-1354
https://jira.iohk.io/browse/CAD-1355
Now contains Basic Auth that checks users from the database and can be turned off.
@disassembler :point_up: 
**By default Basic Auth disabled!**
=> [CAD-1354] Add blacklisting functionality.

doc/getting-started/running.md
https://jira.iohk.io/browse/CAD-1360
This is using Nix as the go-to method, as Kevin wanted.
The problem is that Nix is currently having issues, so that will be resolved a bit later.
=> [CAD-1360] Add documentation for third party clients.

ChangeLog.md, README.md, cabal.project, config/testnet-config.yaml, nix/default.nix, nix/nixos/smash-service.nix, nix/nixos/tests/smash-test.nix, nix/regenerate.sh, nix/sources.json, smash.cabal, src/Cardano/Db/Schema.hs, src/Cardano/SmashDbSync.hs, src/DbSyncPlugin.hs, src/Lib.hs, stack.yaml, stack.yaml.lock, test/SmashSpecSM.hs
https://jira.iohk.io/browse/CAD-1404
=> [CAD-1404] Create 1.0.0 release.

ChangeLog.md, README.md, smash.cabal
https://jira.iohk.io/browse/CAD-1404
=> [CAD-1404] Fix version and update comments.

README.md, doc/getting-started/running.md, schema/migration-2-0001-20200810.sql, src/Cardano/Db/Schema.hs
https://jira.iohk.io/browse/CAD-1456
Do note the test example in README.md under "How to test delisting?".
=> [CAD-1456] Implement blacklisting for pool ids.

ChangeLog.md, README.md, smash.cabal
https://jira.iohk.io/browse/CAD-1468
=> [CAD-1468] Create 1.0.0. release, MVP.

smash.cabal, src/Cardano/Db/Database.hs, src/Cardano/Db/Query.hs, src/Cardano/Metrics.hs, src/Cardano/SmashDbSync.hs
https://jira.iohk.io/browse/CAD-1471
=> [CAD-1471] Query pool id along with hash when looking for pool info.

cabal.project, src/DbSyncPlugin.hs, stack.yaml
https://jira.iohk.io/browse/CAD-1791
Tested on `shelly-qa`, `mc4` and `mainnet`.
@jbgi confirmed that this solved the issue on `shelly-qa`.
=> [CAD-1791] smash on shelley-qa is failing when decoding address.

nix/haskell.nix
=> Disable basic auth for the nix build and nixos service

src/Lib.hs
https://jira.iohk.io/browse/CAD-736
Implemented caching on GET for the metadata, which is the only place where we can have full-blown caching without querying the server.
=> [CAD-1358] Return the caching headers for the HTTP server to work with that.

config/mainnet-config.yaml, config/testnet-config.yaml, src/Cardano/SmashDbSync.hs
https://jira.iohk.io/browse/CAD-2088
Fixed the paths of the genesis files to be relative to the config file.
=> [CAD-2088] Resolve paths relative to the config file, not the executable

src/Lib.hs, src/Types.hs
https://jira.iohk.io/browse/CAD-2074
Can be seen by:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/status
{"status":"OK","version":"1.1.0"}           
```
=> [CAD-2074] Health check endpoint.

app/Main.hs, smash.cabal, src/Cardano/SMASH/API.hs, src/Cardano/SMASH/DB.hs, src/Cardano/SMASH/DBSync/Db/Database.hs, src/Cardano/SMASH/DBSync/Db/Delete.hs, src/Cardano/SMASH/DBSync/Db/Error.hs, src/Cardano/SMASH/DBSync/Db/Insert.hs, src/Cardano/SMASH/DBSync/Db/Migration.hs, src/Cardano/SMASH/DBSync/Db/Migration/Haskell.hs, src/Cardano/SMASH/DBSync/Db/Migration/Version.hs, src/Cardano/SMASH/DBSync/Db/PGConfig.hs, src/Cardano/SMASH/DBSync/Db/Query.hs, src/Cardano/SMASH/DBSync/Db/Run.hs, src/Cardano/SMASH/DBSync/Db/Schema.hs, src/Cardano/SMASH/DBSync/Db/Types.hs, src/Cardano/SMASH/DBSync/Metrics.hs, src/Cardano/SMASH/DBSync/SmashDbSync.hs, src/Cardano/SMASH/DBSyncPlugin.hs, src/Cardano/SMASH/FetchQueue.hs, src/Cardano/SMASH/FetchQueue/Retry.hs, src/Cardano/SMASH/Lib.hs, src/Cardano/SMASH/Offline.hs, src/Cardano/SMASH/Types.hs, test/SmashSpec.hs, test/SmashSpecSM.hs
https://jira.iohk.io/browse/CAD-2093
Refactoring to improve reuse as a library.
=> [CAD-2093] Use qualified module names.

app/Main.hs, smash.cabal, src/Cardano/SMASH/API.hs
We missed a build failure when testing mode is enabled. I also added a way to disable cardano-db-sync dependency, which is important for the wallet.
=> Two follow-up fixes

src/Cardano/SMASH/DB.hs, src/Cardano/SMASH/DBSyncPlugin.hs, src/Cardano/SMASH/Lib.hs, test/SmashSpec.hs, test/SmashSpecSM.hs
https://jira.iohk.io/browse/CAD-1356
We still need to fix the types for the fetch error before adding this, will be done in subsequent PRs.
=> [CAD-1356] Add tests for the existing functionality.

README.rst, nix/haskell.nix, release.nix, smash/app/Main.hs, smash/smash.cabal, smash/src/Cardano/SMASH/DB.hs, smash/src/Cardano/SMASH/DBSync/Db/Query.hs, smash/src/Cardano/SMASH/DBSync/Db/Schema.hs, smash/src/Cardano/SMASH/DBSyncPlugin.hs, smash/src/Cardano/SMASH/Offline.hs, smash/test/DBSpec.hs, smash/test/MigrationSpec.hs
https://jira.iohk.io/browse/CAD-2153
=> [CAD-2153] In-memory database.

config/shelley-qa-config.yaml, config/shelley_qa-byron-genesis.json, config/shelley_qa-shelley-genesis.json, smash/app/Main.hs, smash/smash.cabal, smash/src/Cardano/SMASH/DBSync/Db/Migration.hs, smash/src/Cardano/SMASH/DBSync/SmashDbSync.hs, smash/src/Cardano/SMASH/Lib.hs
https://jira.iohk.io/browse/CAD-2152
Tested with absolute directory (Nix genesis files) and relative directories, both work correctly, tested with `shelley_qa` node version `1.21.1`.
=> [CAD-2152] Fix testnet configuration and add configs for shelley_qa.

doc/getting-started/how-to-install-smash.md, doc/getting-started/how-to-run-smash.md, smash-servant-types/src/Cardano/SMASH/API.hs, smash-servant-types/src/Cardano/SMASH/DBSync/Db/Types.hs, smash-servant-types/src/Cardano/SMASH/Types.hs, smash/app/Main.hs, smash/src/Cardano/SMASH/DB.hs, smash/src/Cardano/SMASH/DBSync/Db/Insert.hs, smash/src/Cardano/SMASH/DBSync/Db/Query.hs, smash/src/Cardano/SMASH/DBSync/Db/Schema.hs, smash/src/Cardano/SMASH/Lib.hs, smash/src/Cardano/SMASH/Offline.hs, smash/test/SmashSpec.hs, smash/test/SmashSpecSM.hs
https://jira.iohk.io/browse/CAD-2182
Also fixed the types from the DB, simplified.
=> [CAD-2182] Pool insertion and ticker insertion should be added into API.

doc/getting-started/how-to-install-smash.md, doc/getting-started/how-to-run-smash.md, smash/app/Main.hs, smash/src/Cardano/SMASH/DB.hs, smash/src/Cardano/SMASH/DBSync/Db/Delete.hs, smash/src/Cardano/SMASH/DBSync/Db/Insert.hs, smash/src/Cardano/SMASH/DBSync/Db/Schema.hs, smash/src/Cardano/SMASH/Lib.hs
https://jira.iohk.io/browse/CAD-2183
Testing can be done by adding an admin user:
```
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- create-admin-user --username ksaric --password cirask
```
And removing an admin user:
```
SMASHPGPASSFILE=config/pgpass stack run smash-exe -- delete-admin-user --username ksaric --password cirask
```
=> [CAD-2183] Add/remove admin user via CLI.

smash-servant-types/src/Cardano/SMASH/Types.hs
https://jira.iohk.io/browse/CAD-2177
The API is backward compatible so we don't have to bump up the API version.
Example with regular pool id:
```
$> curl --verbose --header "Content-Type: application/json" --request GET http://localhost:3100/api/v1/errors/fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38 | jq .
[
{
"time": "23.11.2020. 08:30:01",
"retryCount": 0,
"poolHash": "93cf2f2fead6c419ccaae1a41f0786de4b9daefea7074d7bda3d288e76e20a97",
"cause": "HTTP Exception from poolId fc80a2a814338475c737df5d1c50253046c8c04eb3663336af7beb38' when fetching metadata from 'https://explorer.shelley-qa.dev.cardano.org/p/3.json' resulted in : InternalException (HandshakeFailed (Error_Protocol (\"certificate rejected: [SelfSigned]\",True,CertificateUnknown)))",
"poolId": …
```
=> [CAD-2177] smash should work also with pool_ids in Bech32 format.

nix/nixos/smash-service.nix, nix/nixos/tests/default.nix, nix/nixos/tests/smash-test.nix, nix/sources.json, release.nix
=> nixos: fix potentialy conflicting option, add testing-mode.

smash/src/Cardano/SMASH/DBSync/SmashDbSync.hs
https://jira.iohk.io/browse/CAD-2408
You can test this by removing the state dir and running SMASH to see if it will correctly create it.
=> [CAD-2408] Create directory for --state-dir automatically if it does not exist.

smash/src/Cardano/SMASH/DBSync/Db/Migration.hs
https://jira.iohk.io/browse/CAD-2416
https://github.com/input-output-hk/smash/issues/88
=> [CAD-2416] Database connection inconsistency.

cabal.project, smash-sync/LICENSE, smash-sync/Setup.hs, smash-sync/smash-sync.cabal, smash-sync/src/Cardano/Sync/SmashDbSync.hs, smash/app/Main.hs, smash/smash.cabal, smash/src/Cardano/SMASH/DBSync/Db/Database.hs, stack.yaml
https://jira.iohk.io/browse/CAD-1798
Not fully removing `db-sync`, but removed a large part of it.
=> [CAD-1357] Remove any traces of cardano-db-sync.

doc/getting-started/how-to-install-smash.md
https://jira.iohk.io/browse/CAD-2180
https://github.com/input-output-hk/smash/issues/50
=> [CAD-2180] Documentation improvements.

config/launchpad-config.yaml, smash-sync/src/Cardano/Sync/SmashDbSync.hs, smash/src/Cardano/SMASH/DB.hs, smash/src/Cardano/SMASH/DBSync/Db/Database.hs, smash/src/Cardano/SMASH/DBSyncPlugin.hs, stack.yaml
https://jira.iohk.io/browse/CAD-2450
Tested on `launchpad`, also fixed a couple of things along the way.
Tested with `1.24.2` and the `mary` network.
=> [CAD-2450] Bump up to Mary (Native tokens) support.

ChangeLog.md, smash-servant-types/smash-servant-types.cabal, smash-sync/smash-sync.cabal, smash/smash.cabal
Release 1.4.0.
PRs (that contain testing instructions):
- https://github.com/input-output-hk/smash/pull/134
- https://github.com/input-output-hk/smash/pull/134
- https://github.com/input-output-hk/smash/pull/137
- https://github.com/input-output-hk/smash/pull/130
- https://github.com/input-output-hk/smash/pull/139
- https://github.com/input-output-hk/smash/pull/142
- https://github.com/input-output-hk/smash/pull/132
- https://github.com/input-output-hk/smash/pull/133
- https://github.com/input-output-hk/smash/pull/140
=> Release 1.4.0

smash/app/Main.hs, smash/smash.cabal, smash/src/Cardano/SMASH/DBSyncPlugin.hs, smash/src/Cardano/SMASH/DBSyncRun.hs, stack.yaml
https://jira.iohk.io/browse/CAD-2060
Fixing the dependencies and updating smash so we can use it from `db-sync` as a plugin.
=> [CAD-2060] Moving and updating dependencies so we can use it in db-sync.

cabal.project, nix/haskell.nix, nix/sources.json, smash/smash.cabal, smash/src/Cardano/SMASH/DBSyncPlugin.hs, stack.yaml
https://jira.iohk.io/browse/CAD-2060
Bumping dependencies for the new version of `db-sync`.
=> [CAD-2060] Bumping dependencies for db-sync.

.gitignore, cabal.project, config/allegra-config.yaml, config/launchpad-config.yaml, config/mainnet-config.yaml, config/pgpass-test, config/shelley-qa-config.yaml, config/testnet-config.yaml, doc/getting-started/how-to-install-smash.md, smash/src/Cardano/SMASH/DBSync/Db/Query.hs, smash/src/Cardano/SMASH/DBSyncRun.hs, smash/src/Cardano/SMASH/Lib.hs, smash/src/Cardano/SMASH/Offline.hs, smash/test/MigrationSpec.hs, stack.yaml
https://jira.iohk.io/browse/CAD-2811
=> [CAD-2811] Fix error handling to show last 10 results by default.

smash/src/Cardano/SMASH/DBSyncPlugin.hs
https://jira.iohk.io/browse/CAD-2832
Temporarily returning ledger state since the chain sync protocol depends on it for syncing.
=> [CAD-2832] Smash syncing from scratch every restart, temporary fix for standalone server.
